### ISSUE TITLE
Migrate to microbundle, storybook, typescript

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms-components#12]

**Comment by LaChope** [comment]
@blcham For SForms I was using TypeScript for all the stories to push it a little bit in the project, should we also set it up in smart-components?

**Comment by blcham** [comment]
> @blcham For SForms I was using TypeScript for all the stories to push it a little bit in the project, should we also set it up in smart-components?

Yes, good point, I updated the description of the task.
