### ISSUE TITLE
Create simple question with typeahead tree answer 

### ISSUE THREAD

**Issue by VojtechLunak** [kbss-cvut/s-forms-components#30]
Create simple question component with typeahead tree answer.

Variants:
- single select
- multi select - **we do not need it now**

Question will have "type-ahead" layout class and will use `IntelligentTreeSelect `component for rendering select with tree-structured options.

**Comment by blcham** [comment]
Closing as it was implemented long time ago and we are now investigating issues related to this ticket -- https://github.com/kbss-cvut/s-forms-components/issues/37
