### ISSUE TITLE
Investigate issues related to displaying type-ahead component

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/s-forms-components#37]
[Type-ahead component](https://s-forms-components-kbss.netlify.app/?path=/story/components-simple-question-with-tree-typeahead-answer--single-select) in single select mode for non-section question behaves wird. It frezes from time to time (mainly when you expand tree nodes)

Most likely related issues:
    https://github.com/kbss-cvut/s-forms-components/issues/31
    https://github.com/kbss-cvut/s-forms-components/issues/29
    https://github.com/kbss-cvut/s-forms/issues/218
    https://github.com/kbss-cvut/s-forms/issues/199
    https://github.com/kbss-cvut/s-forms/issues/181
    https://github.com/kbss-cvut/s-forms/issues/231

A/C:
- find out if the relevant issues are not duplicates and close unnecessary tickets

**Comment by LaChope** [comment]
Reopen as not solved in s-forms-components

**Comment by LaChope** [comment]
@blcham solved when bumped to https://github.com/kbss-cvut/s-forms/pull/232 with **chrome** but does **not** work with **firefox**. I propose to close this ticket and create new one more specific to Firefox.

**Comment by LaChope** [comment]
Closed in favor of #43
